// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/image.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

/// <summary>
///my service is called PingPongService
/// </summary>
public static partial class ImageService
{
  static readonly string __ServiceName = "ImageService";

  static readonly grpc::Marshaller<global::StreamBytes> __Marshaller_StreamBytes = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::StreamBytes.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::EmptyResponse> __Marshaller_EmptyResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EmptyResponse.Parser.ParseFrom);

  static readonly grpc::Method<global::StreamBytes, global::EmptyResponse> __Method_save = new grpc::Method<global::StreamBytes, global::EmptyResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "save",
      __Marshaller_StreamBytes,
      __Marshaller_EmptyResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::ImageReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of ImageService</summary>
  [grpc::BindServiceMethod(typeof(ImageService), "BindService")]
  public abstract partial class ImageServiceBase
  {
    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::EmptyResponse> save(global::StreamBytes request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for ImageService</summary>
  public partial class ImageServiceClient : grpc::ClientBase<ImageServiceClient>
  {
    /// <summary>Creates a new client for ImageService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public ImageServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for ImageService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public ImageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected ImageServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected ImageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::EmptyResponse save(global::StreamBytes request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return save(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::EmptyResponse save(global::StreamBytes request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_save, null, options, request);
    }
    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::EmptyResponse> saveAsync(global::StreamBytes request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return saveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::EmptyResponse> saveAsync(global::StreamBytes request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_save, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override ImageServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new ImageServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(ImageServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_save, serviceImpl.save).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, ImageServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_save, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::StreamBytes, global::EmptyResponse>(serviceImpl.save));
  }

}
#endregion
