// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/pingpong.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

/// <summary>
///my service is called PingPongService
/// </summary>
public static partial class PingPongService
{
  static readonly string __ServiceName = "PingPongService";

  static readonly grpc::Marshaller<global::Ping> __Marshaller_Ping = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ping.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Pong> __Marshaller_Pong = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Pong.Parser.ParseFrom);

  static readonly grpc::Method<global::Ping, global::Pong> __Method_ping = new grpc::Method<global::Ping, global::Pong>(
      grpc::MethodType.Unary,
      __ServiceName,
      "ping",
      __Marshaller_Ping,
      __Marshaller_Pong);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::PingpongReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of PingPongService</summary>
  [grpc::BindServiceMethod(typeof(PingPongService), "BindService")]
  public abstract partial class PingPongServiceBase
  {
    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::Pong> ping(global::Ping request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for PingPongService</summary>
  public partial class PingPongServiceClient : grpc::ClientBase<PingPongServiceClient>
  {
    /// <summary>Creates a new client for PingPongService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public PingPongServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for PingPongService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public PingPongServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected PingPongServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected PingPongServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::Pong ping(global::Ping request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::Pong ping(global::Ping request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_ping, null, options, request);
    }
    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::Pong> pingAsync(global::Ping request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return pingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    ///an example of getting a feature
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::Pong> pingAsync(global::Ping request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_ping, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override PingPongServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new PingPongServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(PingPongServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_ping, serviceImpl.ping).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, PingPongServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_ping, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ping, global::Pong>(serviceImpl.ping));
  }

}
#endregion
